### ISSUE TITLE
Fix vietnamese language link in all README.md files

### ISSUE THREAD

**Issue by gomzyakov** [achvm/achvm.github.io#124]
Like in this PR https://github.com/achvm/achvm.github.io/pull/123, but in all `README.md` files inside subdirectories in https://github.com/achvm/achvm.github.io/tree/main/lang

**Comment by malikaraf** [comment]
Interested to work in this. Should i start?

**Comment by gomzyakov** [comment]
@malikaraf Hello!

Yes, of course! I assigned this issue to you.

**Comment by malikaraf** [comment]
Hi . Got caught up in something. I started on it today and noticed someone else already fixed the broken links. Thanks for assigning it to me regardless!

**Comment by gomzyakov** [comment]
@malikaraf 

Thanks for the response! Yes, the edits were made in PR https://github.com/achvm/achvm.github.io/pull/133
