### ISSUE TITLE
Remove 4 files from `/assets/art` folder

### ISSUE THREAD

**Issue by gomzyakov** [achvm/achvm.github.io#131]
Need to remove this 4 files from folder https://github.com/achvm/achvm.github.io/tree/main/assets/art:

- [github-profile-avatar.png](https://github.com/achvm/achvm.github.io/blob/main/assets/art/github-profile-avatar.png)
- [github-profile-avatar.vectornator](https://github.com/achvm/achvm.github.io/blob/main/assets/art/github-profile-avatar.vectornator)
- [social-preview.png](https://github.com/achvm/achvm.github.io/blob/main/assets/art/social-preview.png)
- [social-preview.vectornator](https://github.com/achvm/achvm.github.io/blob/main/assets/art/social-preview.vectornator)

**Comment by mohamedhesham221** [comment]
You just wanna to delete them from `assets/art` folder ?

**Comment by gomzyakov** [comment]
@mohamedhesham221 Hello! Yes, just delete)
