### ISSUE TITLE
The gold "Pair Extraordinaire" PR count

### ISSUE THREAD

**Issue by spageektti** [achvm/achvm.github.io#58]
Hi, there may be an issue with the number of commits needed for the badge (48). As the maintainer of TLDR Pages, I have numerous co-authored commits on merged pull requests, yet I received the gold badge today. 

In reality, I have 180 commits in [this repository](https://github.com/tldr-pages/tldr/graphs/contributors), but only 108 or fewer (I opened PRs in other repositories too) of those are solely authored by me, corresponding to the total number of my merged pull requests. So all the others are those I coauthored. Additionally, I have co-authored commits in other repositories, and some of my pull requests include commits co-authored by others, which also contribute to the count.

**Comment by BadmusQudusAyomide** [comment]
thats cool

**Comment by ssakuraki** [comment]
I think, it's neccessary
